### ISSUE TITLE
Filters doesn't work :  Array to string conversion 

### ISSUE THREAD

**Issue by anardil** [aimeos/aimeos#73] opened 2021-11-23 12:31 UTC
Hello,

I did a fresh install of Aimeos package and all works fine apparenly but when I want filter products in front, I've got this error:

Version PHP 8

My requires in composer.json

```
    "require": {
        "php": "^7.3||^8.0",
        "aimeos-themes/rvdtheme": "dev-master",
        "aimeos/ai-cms-grapesjs": "2021.10.*",
        "aimeos/aimeos-laravel": "2021.10.*",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.54",
        "laravel/sanctum": "^2.11",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.0"
    },

```

```

ErrorException
Array to string conversion
http://127.0.0.1:8000/shop?f_supid%5B0%5D=2 

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/aimeos/aimeos-core/lib/mwlib/src/MW/View/Helper/Link/Standard.php:43
```

<img width="1268" alt="Capture d’écran 2021-11-23 à 13 24 04" src="https://user-images.githubusercontent.com/471437/143024015-5f37d394-8cf0-47e4-930f-374d0e0a7b80.png">

Can you tell me how to fix this error, please?
Thank you.

Regards.

**Comment by aimeos** [comment] 2021-11-23 13:22
We can't reproduce the issue. Did you overwrite templates in your own extension?

**Comment by anardil** [comment] 2021-11-23 13:23
Hello,

No I did nothing for the moment in my own extension.

Regards.

**Comment by aimeos** [comment] 2021-11-23 13:24
Can you please post the output of `composer show`?

**Comment by anardil** [comment] 2021-11-23 13:25
```
aimeos-themes/rvdtheme             dev-master Aimeos rvdtheme extension
aimeos/ai-admin-jqadm              2021.10.5  Aimeos Vue.js+Bootstrap admin interface
aimeos/ai-admin-jsonadm            2021.10.3  Aimeos ai-admin-jsonadm extension
aimeos/ai-client-html              2021.10.6  Aimeos ai-client-html extension
aimeos/ai-client-jsonapi           2021.10.2  Aimeos JSON API extension
aimeos/ai-cms-grapesjs             2021.10.1  Aimeos GrapesJS CMS extension
aimeos/ai-controller-frontend      2021.10.3  Aimeos ai-controller-frontend extension
aimeos/ai-controller-jobs          2021.10.4  Aimeos ai-controller-jobs extension
aimeos/ai-gettext                  2021.10.2  Aimeos Gettext extension
aimeos/ai-laravel                  2021.10.1  Laravel adapter for Aimeos web shops and e-commerce solutions
aimeos/ai-swiftmailer              2021.10.1  SwiftMailer adapter for Aimeos web shops and e-commerce solutions
aimeos/aimeos-core                 2021.10.8  Full-featured e-commerce components for high performance online shops
aimeos/aimeos-laravel              2021.10.3  Professional, full-featured and high performance Laravel e-commerce package for online shops and complex B2B projects
aimeos/map                         2.4.0      Easy and elegant handling of PHP arrays as array-like map objects similar to jQuery and Laravel Collections
asm89/stack-cors                   v2.0.3     Cross-origin resource sharing library and stack middleware
brick/math                         0.9.3      Arbitrary-precision arithmetic library
dflydev/dot-access-data            v3.0.1     Given a deep data structure, access data by dot notation.
doctrine/cache                     2.1.1      PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache...
doctrine/dbal                      2.13.5     Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/deprecations              v0.5.3     A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or sel...
doctrine/event-manager             1.1.1      The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                 2.0.4      PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singul...
doctrine/instantiator              1.4.0      A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                     1.2.1      PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
dragonmantank/cron-expression      v3.1.0     CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
egulias/email-validator            2.1.25     A library for validating emails against several RFCs
enshrined/svg-sanitize             0.14.1     An SVG sanitizer for PHP
facade/flare-client-php            1.9.1      Send PHP errors to Flare
facade/ignition                    2.16.1     A beautiful error page for Laravel applications.
facade/ignition-contracts          1.0.2      Solution contracts for Ignition
fakerphp/faker                     v1.16.0    Faker is a PHP library that generates fake data for you.
filp/whoops                        2.14.4     php error handling for cool kids
fruitcake/laravel-cors             v2.0.4     Adds CORS (Cross-Origin Resource Sharing) headers support in your Laravel application
graham-campbell/result-type        v1.0.4     An Implementation Of The Result Type
guzzlehttp/guzzle                  7.4.0      Guzzle is a PHP HTTP client library
guzzlehttp/promises                1.5.1      Guzzle promises library
guzzlehttp/psr7                    2.1.0      PSR-7 message implementation that also provides common utility methods
hamcrest/hamcrest-php              v2.0.1     This is the PHP port of Hamcrest Matchers
laminas/laminas-diactoros          2.8.0      PSR HTTP Message implementations
laravel/framework                  v8.73.1    The Laravel Framework.
laravel/sail                       v1.12.5    Docker files for running a basic Laravel application.
laravel/sanctum                    v2.12.2    Laravel Sanctum provides a featherweight authentication system for SPAs and simple APIs.
laravel/serializable-closure       v1.0.4     Laravel Serializable Closure provides an easy and secure way to serialize closures in PHP.
laravel/tinker                     v2.6.2     Powerful REPL for the Laravel framework.
laravel/ui                         v3.3.3     Laravel UI utilities and presets.
league/commonmark                  2.0.2      Highly-extensible PHP Markdown parser which fully supports the CommonMark spec and GitHub-Flavored Markdown (GFM)
league/config                      v1.1.1     Define configuration arrays with strict schemas and access values with dot notation
league/flysystem                   1.1.6      Filesystem abstraction: Many filesystems, one API.
league/mime-type-detection         1.9.0      Mime-type detection for Flysystem
mockery/mockery                    1.4.4      Mockery is a simple yet flexible PHP mock object framework
monolog/monolog                    2.3.5      Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                  1.10.2     Create deep copies (clones) of your objects
nesbot/carbon                      2.54.0     An API extension for DateTime that supports 281 different languages.
nette/schema                       v1.2.2     📐 Nette Schema: validating data structures against a given Schema.
nette/utils                        v3.2.5     🛠  Nette Utils: lightweight utilities for string & array manipulation, image handling, safe JSON encoding/decoding, va...
nikic/php-parser                   v4.13.1    A PHP parser written in PHP
nunomaduro/collision               v5.10.0    Cli error handling for console/command-line PHP applications.
nyholm/psr7                        1.4.1      A fast PHP7 implementation of PSR-7
opis/closure                       3.6.2      A library that can be used to serialize closures (anonymous functions) and arbitrary objects.
phar-io/manifest                   2.0.3      Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    3.1.0      Library for handling version information and constraints
php-http/message-factory           v1.0.2     Factory interfaces for PSR-7 HTTP Message
phpdocumentor/reflection-common    2.2.0      Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  5.3.0      With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that i...
phpdocumentor/type-resolver        1.5.1      A PSR-5 based resolver of Class names, Types and Structural Element Names
phpoption/phpoption                1.8.0      Option Type for PHP
phpspec/prophecy                   1.14.0     Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          9.2.9      Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          3.0.5      FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                3.1.1      Invoke callables with a timeout
phpunit/php-text-template          2.0.4      Simple template engine.
phpunit/php-timer                  5.0.3      Utility class for timing
phpunit/phpunit                    9.5.10     The PHP Unit Testing framework.
psr/container                      1.1.2      Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher               1.0.0      Standard interfaces for event handling.
psr/http-client                    1.0.1      Common interface for HTTP clients
psr/http-factory                   1.0.1      Common interfaces for PSR-7 HTTP message factories
psr/http-message                   1.0.1      Common interface for HTTP messages
psr/log                            2.0.0      Common interface for logging libraries
psr/simple-cache                   1.0.1      Common interfaces for simple caching
psy/psysh                          v0.10.9    An interactive shell for modern PHP.
ralouphie/getallheaders            3.0.3      A polyfill for getallheaders.
ramsey/collection                  1.2.2      A PHP library for representing and manipulating collections.
ramsey/uuid                        4.2.3      A PHP library for generating and working with universally unique identifiers (UUIDs).
sebastian/cli-parser               1.0.1      Library for parsing CLI options
sebastian/code-unit                1.0.8      Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup 2.0.3      Looks up which function or method a line of code belongs to
sebastian/comparator               4.0.6      Provides the functionality to compare PHP values for equality
sebastian/complexity               2.0.2      Library for calculating the complexity of PHP code units
sebastian/diff                     4.0.4      Diff implementation
sebastian/environment              5.1.3      Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 4.0.4      Provides the functionality to export PHP variables for visualization
sebastian/global-state             5.0.3      Snapshotting of global state
sebastian/lines-of-code            1.0.3      Library for counting the lines of code in PHP source code
sebastian/object-enumerator        4.0.4      Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         2.0.4      Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        4.0.4      Provides functionality to recursively process PHP variables
sebastian/resource-operations      3.0.3      Provides a list of PHP built-in functions that operate on resources
sebastian/type                     2.3.4      Collection of value objects that represent the types of the PHP type system
sebastian/version                  3.0.2      Library that helps with managing the version number of Git-hosted PHP projects
swiftmailer/swiftmailer            v6.3.0     Swiftmailer, free feature-rich PHP mailer
symfony/console                    v5.3.11    Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v5.3.4     Converts CSS selectors to XPath expressions
symfony/deprecation-contracts      v2.5.0     A generic function and convention to trigger deprecation notices
symfony/error-handler              v5.3.11    Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.3.11    Provides tools that allow your application components to communicate with each other by dispatching events and listening ...
symfony/event-dispatcher-contracts v2.5.0     Generic abstractions related to dispatching event
symfony/finder                     v5.3.7     Finds files and directories via an intuitive fluent interface
symfony/http-client-contracts      v2.5.0     Generic abstractions related to HTTP clients
symfony/http-foundation            v5.3.11    Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.3.11    Provides a structured process for converting a Request into a Response
symfony/mime                       v5.3.11    Allows manipulating MIME messages
symfony/polyfill-ctype             v1.23.0    Symfony polyfill for ctype functions
symfony/polyfill-iconv             v1.23.0    Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme     v1.23.1    Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn          v1.23.0    Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.23.0    Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.23.1    Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.23.0    Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.23.0    Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.23.1    Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.23.0    Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                    v5.3.11    Executes commands in sub-processes
symfony/psr-http-message-bridge    v2.1.2     PSR HTTP message bridge
symfony/routing                    v5.3.11    Maps an HTTP request to a set of configuration variables
symfony/service-contracts          v2.5.0     Generic abstractions related to writing services
symfony/string                     v5.3.10    Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                v5.3.11    Provides tools to internationalize your application
symfony/translation-contracts      v2.5.0     Generic abstractions related to translation
symfony/var-dumper                 v5.3.11    Provides mechanisms for walking through any arbitrary PHP variable
tecnickcom/tcpdf                   6.4.2      TCPDF is a PHP class for generating PDF documents and barcodes.
theseer/tokenizer                  1.2.1      A small library for converting tokenized PHP source code into XML and potentially other formats
tijsverkoyen/css-to-inline-styles  2.2.3      CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with inline styles. This ...
vlucas/phpdotenv                   v5.4.0     Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
voku/portable-ascii                1.5.6      Portable ASCII library - performance optimized (ascii) string functions for php.
webmozart/assert                   1.10.0     Assertions to validate method input/output with nice error messages.
```

**Comment by anardil** [comment] 2021-11-23 13:31
If I change this

`$params = array_diff( $params, array_flip( $filter ) );`

by 

`$params = $filter ? array_diff($params, array_flip($filter)) : $params;`

It works.
Regards.

**Comment by aimeos** [comment] 2021-11-23 13:33
Where did you change that? Can you point out the line in the repo?
https://github.com/aimeos/ai-client-html

**Comment by anardil** [comment] 2021-11-23 13:34
I did thaht just for debugging.
It's on vendor/aimeos/aimeos-core/lib/mwlib/src/MW/View/Helper/Link/Standard.php:43

Regards.

**Comment by aimeos** [comment] 2021-11-23 13:49
That is not the real source of the problem. Can you post a screenshot of at least two frames before in the error page (left side are the frames and you can click on those with the "+").

**Comment by anardil** [comment] 2021-11-23 14:12
Ok I understood when the problem happens.
I removed some segment in the URL 

I did that:

`http://127.0.0.1:8000/shop/`

instead of

`http://127.0.0.1:8000/shop/Home~1`

I think it will better to have a redirection to the category "Home" to avoid this problem.

Regards.

**Comment by aimeos** [comment] 2021-11-23 14:38
No, that's not the problem. `http://127.0.0.1:8000/shop/` must work too because it returns the produc list regardless of any categories.

If you can post more screenshots from the debug, we can see where the real problem is.

**Comment by anardil** [comment] 2021-11-23 14:45
Here screenshot before:
<img width="1069" alt="Capture d’écran 2021-11-23 à 15 43 59" src="https://user-images.githubusercontent.com/471437/143045437-d0f12519-d540-4124-8c4a-9dd979f81200.png">
And after color selected:

<img width="1066" alt="Capture d’écran 2021-11-23 à 15 42 48" src="https://user-images.githubusercontent.com/471437/143045543-600f4181-d8a3-4cff-8e1f-83f90f0ef575.png">

**Comment by aimeos** [comment] 2021-11-23 14:58
No, we need a screenshot if click on "(+) 1 vendor frame" on the left of your last screenshot

**Comment by anardil** [comment] 2021-11-23 15:25
<img width="1260" alt="Capture d’écran 2021-11-23 à 16 25 00" src="https://user-images.githubusercontent.com/471437/143052632-6eb02122-ea55-4717-954a-ffa62e86f769.png">

**Comment by aimeos** [comment] 2021-11-23 15:29
Hm, same as before. Can you please click on "Share" in the menu and post the link?

**Comment by AdrianEcode** [comment] 2021-12-09 19:41
Hi! I have the same error. I can't Share with flare in this moment:

![Captura de pantalla 2021-12-09 a las 20 36 11](https://user-images.githubusercontent.com/66115358/145464211-7ecdbc19-8edf-4108-b758-0903fdebdd14.png)

But i can share with you the laravel.log, I hope this will be helpful in resolving the error:

```
[2021-12-09 19:31:11] local.ERROR: Array to string conversion {"exception":"[object] (ErrorException(code: 0): Array to string conversion at /Applications/MAMP/htdocs/myshop/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/View/Helper/Link/Standard.php:43)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Array to string...', '/Applications/M...', 43, Array)
#1 /Applications/MAMP/htdocs/myshop/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/View/Helper/Link/Standard.php(43): array_diff(Array, Array)
#2 [internal function]: Aimeos\\MW\\View\\Helper\\Link\\Standard->transform('client/html/cat...', Array)
#3 /Applications/MAMP/htdocs/myshop/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/View/Standard.php(88): call_user_func_array(Array, Array)
#4 /Applications/MAMP/htdocs/myshop/vendor/aimeos/ai-client-html/client/html/templates/catalog/filter/body-standard.php(90): Aimeos\\MW\\View\\Standard->__call('link', Array)
#5 /Applications/MAMP/htdocs/myshop/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/View/Standard.php(282): include('/Applications/M...')
#6 /Applications/MAMP/htdocs/myshop/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/View/Standard.php(264): Aimeos\\MW\\View\\Standard->includeFile('/Applications/M...')
#7 /Applications/MAMP/htdocs/myshop/vendor/aimeos/ai-client-html/client/html/src/Client/Html/Catalog/Filter/Standard.php(233): Aimeos\\MW\\View\\Standard->render('catalog/filter/...')
#8 /Applications/MAMP/htdocs/myshop/vendor/aimeos/ai-client-html/client/html/src/Client/Html/Common/Decorator/Base.php(104): Aimeos\\Client\\Html\\Catalog\\Filter\\Standard->getBody('')
#9 /Applications/MAMP/htdocs/myshop/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Controller/CatalogController.php(96): Aimeos\\Client\\Html\\Common\\Decorator\\Base->getBody()
#10 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Aimeos\\Shop\\Controller\\CatalogController->listAction()
#11 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('listAction', Array)
#12 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Aimeos\\Shop\\Controller\\CatalogController), 'listAction')
#13 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#14 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#15 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#24 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#32 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#33 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#34 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#35 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Applications/MAMP/htdocs/myshop/app/Http/Middleware/SetLocale.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\SetLocale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Applications/MAMP/htdocs/myshop/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /Applications/MAMP/htdocs/myshop/app/Http/Middleware/TrustHosts.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\TrustHosts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#56 /Applications/MAMP/htdocs/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#57 /Applications/MAMP/htdocs/myshop/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#58 /Applications/MAMP/htdocs/myshop/server.php(21): require_once('/Applications/M...')
#59 {main}
"} 
```

**Comment by aimeos** [comment] 2021-12-10 07:38
Thanks for the stack trace!
What is the URL in the browser address line when the error occurs?

**Closed** 2022-04-11 17:07 UTC
